	<ol class="breadcrumb">
  		<li><a href="<?php echo APP_URL?>">Home</a></li>
		<li><a href="admincp.php">Control Panel</a></li>
		<li class="active">Status</li>
	</ol>
	
	<div id="global-notifications" class="container-fluid hide"></div>
	
	<div role="tabpanel" class="tab-content">
		<section class="container-fluid tab-pane active" role="tabpanel" id="status">
			<div class="page-header"><h2>GitLab Instance</h2></div>
			<form class="form-horizontal">
				<div class="form-group">
					<label class="col-sm-2 control-label">GitLab Url</label>
					<div class="col-sm-10">
						<input type="text" class="form-control" id="GitLabUrl" value="<?php echo GITLAB_URL?>">
						<span class="help-block"><a href="<?php echo GITLAB_URL?>" target="_blank">Open in new window</a></span>
					</div>
				</div>
				<div class="form-group">
					<label class="col-sm-2 control-label">GitLab Private Token</label>
					<div class="col-sm-10">
						<input type="text" class="form-control" id="GitLabPrivateToken" value="<?php echo $GitLab_PrivateToken?>">
					</div>
				</div>
				<div class="form-group">
					<label class="col-sm-2 control-label">GitLab Root User</label>
					<div class="col-sm-10">
						<input type="text" class="form-control" id="GitLabRootUsername" value="<?php echo GITLAB_ADMIN_USER ?>">
					</div>
				</div>
			</form>
			<div id="StatusResult" class="container-fluid hide"></div>
		</section>
		<section class="container-fluid tab-pane" role="tabpanel" id="new-users">
			<div class="page-header"><h2>Import Users</h2></div>
			<form id="formNewUser" class="form-horizontal">
				<div class="alert alert-info">
					<span class="glyphicon glyphicon-info-sign" aria-hidden="true"></span> 
					Passwords will be randomly generated. After users are created, make an announcement to the users asking them to use &quot;forget password&quot; to reset their passwords. By doing so a &quot;reset password&quot; email will be sent to their associated email addresses.
				</div>
				<div class="form-group">
					<label class="col-sm-2 control-label">CSV data</label>
					<div class="col-sm-10">
						<textarea class="form-control" id="NewUserCsvBlock" name="CsvData" rows="4"></textarea>
						<span class="help-block">Copy and paste the roster here. The first line should be the table header. The following columns are <strong>required</strong> to match the required GitLab user fields: <code>User ID</code> for <em>username</em>, <code>NAME</code> for <em>name</em>, <code>EMAIL</code> for <em>email</em>. If there is a <code>ID</code> column, it will be mapped to <code>extern_uid</code> field. Roster csv from <tt>Sungard Higher Education</tt> system can be pasted directly.</span>
					</div>
				</div>
				<div class="form-group">
					<label for="inputProjectsLimit" class="col-sm-2 control-label">Project limit</label>
					<div class="col-sm-10">
						<input type="number" class="form-control" id="inputProjectsLimit" name="ProjectsLimit" placeholder="16" value="16" required="required">
						<span class="help-block">The number of projects each user can have. A non-positive number means no limit.</span>
					</div>
				</div>
				<div class="form-group">
					<label class="col-sm-2 control-label">Options</label>
					<div class="col-sm-10">
						<div class="checkbox">
							<label>
								<input type="checkbox" id="Opt_CanCreateGroup" value="true"> Users are allowed to create their groups.
							</label>
						</div>
						<div class="checkbox">
							<label>
								<input type="checkbox" id="Opt_IsAdmin" value="true"> Users created will be GitLab admins.
							</label>
						</div>
					</div>
				</div>
				<div class="form-group">
					<div class="col-sm-offset-2 col-sm-10">
						<button id="BtnStartCreateNewUsers" class="btn btn-default">Start</button>
					</div>
				</div>
			</form>
			<div id="CreateNewUsersResult" class="container-fluid hide"></div>
		</section>
		<section class="container-fluid tab-pane" role="tabpanel" id="delete-users">
			<div class="page-header"><h2>Delete Users</h2></div>
			<div class="alert alert-info">
				<ul>
					<li>gitlab-ag will NOT delete the root user.</li>
					<li>GitLab API may not return all users due to pagination. You may need to repeat the operation multiple times to ensure the task is fully completed.</li>
					<li>To delete all users and groups, run <code>sudo gitlab-ctl remove_users</code> on your GitLab server.</li>
				</ul>
			</div>
			<form class="form-horizontal">
				<div class="form-group">
					<label for="inputUsernamePattern" class="col-sm-2 control-label">Username Pattern</label>
					<div class="col-sm-10">
						<input type="text" class="form-control" id="inputUsernamePattern" value="*" required="required">
						<span class="help-block">Supports wildcard expression.</span>
					</div>
				</div>
				<div class="form-group">
					<label class="col-sm-2 control-label">Options</label>
					<div class="col-sm-10">
						<div class="checkbox">
							<label>
								<input type="checkbox" id="OptShowNormalUsers" value="true" checked="true"> Match ordinary users.
							</label>
						</div>
						<div class="checkbox">
							<label>
								<input type="checkbox" id="OptShowAdmin" value="true"> Match admin users.
							</label>
						</div>
					</div>
				</div>
				<div class="form-group">
					<div class="col-sm-offset-2 col-sm-10">
						<button id="BtnListMatchedUsers" class="btn btn-default">List matched Users</button>
						<button id="BtnDeleteMatchedUsers" class="btn btn-warning hide">Delete Listed Users</button>
					</div>
				</div>
			</form>
			<div id="DeleteUserResult"></div>
		</section>
		<section class="container-fluid tab-pane" role="tabpanel" id="new-repo">
			<div class="page-header"><h2>New Repositories</h2></div>
			<form class="form-horizontal" id="new-repo-form">
				<div class="form-group">
					<label for="inputProjectOwnerUsernamePattern" class="col-sm-2 control-label">Username Pattern</label>
					<div class="col-sm-10">
						<input type="text" class="form-control" id="inputProjectOwnerUsernamePattern" value="*" required="required">
						<span class="help-block">The target project will be created only for users whose usernames match the pattern. Supports wildcard expression.</span>
					</div>
				</div>
				<div class="form-group">
					<label for="inputNewProjectName" class="col-sm-2 control-label">Project Name</label>
					<div class="col-sm-10">
						<input type="text" class="form-control" id="inputNewProjectName" placeholder="cs240-lab1" required="required">
						<span class="help-block">Name of the project to create.</span>
					</div>
				</div>
				<div class="form-group">
					<label for="inputImportUrl" class="col-sm-2 control-label">Import URL</label>
					<div class="col-sm-10">
						<input type="text" class="form-control" id="inputImportUrl" placeholder="http://username:password@gitlab.com/company/project.git">
						<span class="help-block">Import content from an existing Git repository. On GitLab an import will time out after 4 minutes.</span>
					</div>
				</div>
				<div class="form-group">
					<label for="inputNewProjectDescription" class="col-sm-2 control-label">Project Description</label>
					<div class="col-sm-10">
						<textarea class="form-control" id="inputNewProjectDescription" placeholder="Short description for the project, or leave blank."></textarea>
						<span class="help-block"></span>
					</div>
				</div>
				<div class="form-group">
					<label for="inputVisibilityLevel" class="col-sm-2 control-label">Visibility Level</label>
					<div class="col-sm-10">
						<label class="radio-inline">
							<input type="radio" name="inputVisibilityLevel" id="inputVisibilityLevel1" value="0" checked="true"> Private
						</label>
						<label class="radio-inline">
							<input type="radio" name="inputVisibilityLevel" id="inputVisibilityLevel2" value="10"> Internal
						</label>
						<label class="radio-inline">
							<input type="radio" name="inputVisibilityLevel" id="inputVisibilityLevel3" value="20"> Public
						</label>
					</div>
				</div>
				<div class="form-group">
					<label class="col-sm-2 control-label">Options</label>
					<div class="col-sm-10">
						<div class="checkbox">
							<label>
								<input type="checkbox" id="OptNewProjectEnableIssueTracker" value="true" checked="true"> Enable issue tracker for the projects to create.
							</label>
						</div>
						<div class="checkbox">
							<label>
								<input type="checkbox" id="OptNewProjectEnableMergeRequests" value="true"> Enable merge requests for the projects to create.
							</label>
						</div>
						<div class="checkbox">
							<label>
								<input type="checkbox" id="OptNewProjectEnableWiki" value="true" checked="true"> Enable wiki for the projects to create.
							</label>
						</div>
						<div class="checkbox">
							<label>
								<input type="checkbox" id="OptNewProjectEnableSnippets" value="true"> Enable snippets for the projects to create.
							</label>
						</div>
					</div>
				</div>
				<div class="form-group">
					<div class="col-sm-offset-2 col-sm-10">
						<button type="button" id="BtnListNewProjectMatchedUsers" class="btn btn-default">List matched Users</button>
						<button type="submit" id="BtnCreateNewProjects" class="btn btn-warning hide">Create Projects</button>
					</div>
				</div>
			</form>
			<div id="CreateProjectResult"></div>
			<div id="CreateProjectUsernameMatchingResult"></div>
		</section>
		<section class="container-fluid tab-pane" role="tabpanel" id="edit-repo">
			<div class="page-header"><h2>Edit Repositories</h2></div>
		</section>
		<section class="container-fluid tab-pane" role="tabpanel" id="log">
			<div class="page-header"><h2>Log</h2></div>
		</section>
		<section class="container-fluid tab-pane" role="tabpanel" id="log-select-events">
			<div class="page-header"><h2>Select Loggers</h2></div>
		</section>
	</div>
	
