<?php
/**
 * Render an info prompt page.
 * Three variables must be set:
 * $type: one of {'default, 'info', 'success', 'warning', 'danger'}
 * $title: title of the callout page.
 * $content: description of the callout page. HTML enabled.
 */
?>
<div class="container-fluid">
	<div class="alert alert-<?php echo $type?>" role="alert">
<?php
if ($type == 'success') {
	echo '<span class="glyphicon glyphicon-ok-sign" aria-hidden="true"></span> ';
} else if ($type == 'info') {
	echo '<span class="glyphicon glyphicon-info-sign" aria-hidden="true"></span> ';
} else {
	echo '<span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span> ';
}
?>
		<strong><?php echo $title?>.</strong>
		<?php echo $content?>
	</div>
</div>