		</article>
		<footer>
			<div class="container">
				<p class="text-muted pull-left">
					<a href="http://github.com/xybu/gitlab-ag" target="_blank"><strong>gitlab-ag</strong></a><br />
					GitLab tailored for automated grading
				</p>
				<p class="text-muted pull-right">
					Peak memory usage: <em><?php echo round(memory_get_peak_usage(false)/1024, 4) ?></em> KiB. <br />
					Execution time: <em><?php echo round(microtime() - $GLOBALS['START_TIME'], 4)?></em> ms.
				</p>
			</div>
		</footer>
		<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
		<script src="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.1/js/bootstrap.min.js"></script>
		<script src="//cdnjs.cloudflare.com/ajax/libs/jquery.form/3.51/jquery.form.min.js"></script>
		<script src="//cdnjs.cloudflare.com/ajax/libs/string.js/3.0.0/string.min.js"></script>
		<script src="/ga-assets/ie10-viewport_fix.js"></script>
<?php
if ($script_files != null) {
	foreach ($script_files as $f) 
		echo '<script src="' . $f . '"></script>' . PHP_EOL;
}?>
	</body>
</html>