<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta name="description" content="">
		<meta name="author" content="">
		<title><?php echo $page_title?></title>
		<link rel="dns-prefetch" href="//cdnjs.cloudflare.com/">
		<link href="//cdnjs.cloudflare.com/ajax/libs/bootswatch/3.3.1/sandstone/bootstrap.min.css" rel="stylesheet">
		<link href="/ga-assets/custom.css" rel="stylesheet">
		<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
		<!--[if lt IE 9]>
			<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js"></script>
			<script src="//cdnjs.cloudflare.com/ajax/libs/respond.js/1.4.2/respond.min.js"></script>
		<![endif]-->
	</head>
	<body>
		<nav class="navbar navbar-default navbar-fixed-top">
			<div class="container">
				<div class="navbar-header">
					<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
						<span class="sr-only">Toggle navigation</span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
					<a class="navbar-brand" href="/">gitlab-ag</a>
				</div>
				<div id="navbar" class="navbar-collapse collapse">
					<ul class="nav navbar-nav">
<?php if ($is_user) : ?>
						<li class="active"><a href="#status" class="tab-control">Status</a></li>
						<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Users <span class="caret"></span></a>
							<ul class="dropdown-menu" role="menu">
								<li><a href="#new-users" class="tab-control">Import Users</a></li>
								<li><a href="#delete-users" class="tab-control need-load-user">Delete Users</a></li>
							</ul>
						</li>
						<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Repositories <span class="caret"></span></a>
							<ul class="dropdown-menu" role="menu">
								<li><a href="#new-repo" class="tab-control">Create Repositories</a></li>
								<li><a href="#edit-repo" class="tab-control">Edit Repositories</a></li>
								<li class="divider"></li>
								<li class="dropdown-header">Placeholder</li>
								<li><a href="#">Placeholder</a></li>
							</ul>
						</li>
						<li><a href="#hooks" class="tab-control">Hooks</a></li>
						
<?php endif; ?>
					</ul>
<?php if ($is_user) : ?>
					<ul class="nav navbar-nav navbar-right">
						<li class="active"><a href="admincp.php">Control Panel <span class="sr-only">(current)</span></a></li>
						<li><a href="admincp.php?action=sign_out">Sign Out</a></li>
					</ul>
<?php endif ; ?>
				</div><!--/.nav-collapse -->
			</div>
		</nav>
		<article name="main" class="container-fluid">